article/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name ="article"

urlpatterns = [
    path('dashboard/', views.dashboard, name="dashboard"),
    path('addarticle/', views.addArticle, name="addarticle"),
    path('article/<int:id>', views.detail, name="detail"),
    path('update/<int:id>', views.updateArticle, name="update"),
    path('delete/<int:id>', views.deleteArticle, name="delete"),
    path('', views.articles, name="articles"),
    path('comment/<int:id>', views.addcomment, name="comment"),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.contrib import admin
from django.urls import path,include
from article import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('about/',views.about,name="about"),
    path('articles/', include("article.urls")),
    path('user/', include("user.urls")),
        
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "user"

urlpatterns = [
    path('register/', views.register, name="register"),
    path('login/', views.loginUser, name="login"),
    path('logout/', views.logoutUser, name="logout"),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/models.py
from django.db import models
from ckeditor.fields import RichTextField
# Create your models here.

class Article(models.Model):
    author =models.ForeignKey('auth.User', on_delete=models.CASCADE, verbose_name = "Author")
    title = models.CharField(max_length=50, verbose_name= "Title")
    content = RichTextField(verbose_name="Content")
    created_date= models.DateTimeField(auto_now_add=True, verbose_name="Created Date")
    article_image = models.FileField(blank=True, null=True, verbose_name="Add image")
    def __str__(self):
        return self.title
    class Meta:
        ordering =['-created_date']

class Comment(models.Model):
    article = models.ForeignKey(Article,on_delete=models.CASCADE, verbose_name= "Article", related_name="comments")
    comment_author = models.CharField(max_length=50, verbose_name= "Name")
    comment_content = models.CharField(max_length=200, verbose_name="Comment")
    comment_date= models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.comment_content
    
    class Meta:
        ordering =['-comment_date']

user/models.py
from django.db import models

# Create your models here.

article/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields=["title","content", "article_image"]

user/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(label="Username")
    password = forms.CharField(widget =forms.PasswordInput,label="Password")

class RegisterForm(forms.Form):
    username = forms.CharField(max_length=50, label="Username")
    password = forms.CharField(max_length=20, widget =forms.PasswordInput,label="Password")
    confirm = forms.CharField(max_length=20, widget =forms.PasswordInput,label="Confirm Password")

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        confirm = self.cleaned_data.get("confirm")

        if password and confirm and (password != confirm):
            raise forms.ValidationError("Passwords do not match")
        values = {
            "username": username,
            "password": password        }
        return values

article/views.py
from django.shortcuts import render, HttpResponse,redirect, get_object_or_404,reverse
from django.contrib.auth.decorators import login_required
from .forms import ArticleForm
from django.contrib import messages
from .models import Article, Comment

# Create your views here.

def articles(request):
    keyword = request.GET.get("keyword")
    if keyword:
        articles = Article.objects.filter(title__contains = keyword)
        return render(request,"articles.html",{"articles":articles})
    articles = Article.objects.all()


    return render(request,"articles.html",{"articles":articles})
def index(request):
    return render(request, "index.html")
def about(request):
    return render(request,"about.html")
@login_required(login_url="user:login")
def dashboard(request):
    articles = Article.objects.filter(author=request.user)
    context ={
        "articles":articles
    }
    return render(request,"dashboard.html",context)
@login_required(login_url="user:login")
def addArticle(request):
    form = ArticleForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        article=form.save(commit=False)
        article.author = request.user
        article.save()
        messages.success(request,"Article is added successfully")
        return redirect("article:dashboard")

    return render(request, "addarticle.html",{"form":form})

def detail(request,id):
    #article = Article.objects.filter(id=id).first()
    article = get_object_or_404(Article, id=id)
    comments = article.comments.all()
    return render(request,"detail.html",{"article":article, "comments":comments})
@login_required(login_url="user:login")
def updateArticle(request,id):
    article = get_object_or_404(Article, id=id)
    form = ArticleForm(request.POST or None, request.FILES or None,instance=article)
    if form.is_valid():
        article=form.save(commit=False)
        article.author = request.user
        article.save()
        messages.success(request,"Article is updated successfully")
        return redirect("article:dashboard")
    return render(request,"update.html",{"form":form})
@login_required(login_url="user:login")
def deleteArticle(request,id):
    article = get_object_or_404(Article, id=id)
    article.delete()
    messages.success(request,"Article is deleted successfully")

    return redirect("article:dashboard")

def addcomment(request,id):
    article = get_object_or_404(Article, id=id)
    if request.method == "POST":
        comment_author = request.POST.get("Author")
        comment_content= request.POST.get("Comment")
        newComment = Comment(comment_author=comment_author, comment_content= comment_content)
        newComment.article=article
        newComment.save()
    return redirect(reverse("article:detail",kwargs={"id":id}))

user/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm, LoginForm
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import login,authenticate,logout
# Create your views here.

def register(request):
    form = RegisterForm(request.POST or None)
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")

            newUser = User(username=username)
            newUser.set_password(password)
            newUser.save()
            login(request,newUser)
            messages.info(request,"You are signed up successfully!")
            return redirect("index")
        context = {"form":form}
        return render(request,"register.html", context)
    context = {"form":form}
    return render(request,"register.html", context)
    
def loginUser(request):
    form = LoginForm(request.POST or None)
    context ={
        "form":form
    }
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        user = authenticate(username=username, password=password)
        if user is None:
            messages.info(request,"Username or Password is not correct")
            return render(request,"login.html", context)
        messages.success(request,"You are logged in successfully")
        login(request,user)
        return redirect("index")
    return render (request,"login.html", context)

def logoutUser(request):
    logout(request)
    messages.success(request,"You are now logged out")
    return redirect("index")

templates/about.html
{% extends "layout.html" %}

{% block body %}
<h3>About us</h3>
<hr>

<p>
There was shock last week when Denmark decided to cull all its mink - up to 17 million animals - because of the spread of coronavirus. That national cull has turned into a political outcry, now that the prime minister has admitted the plan was rushed and had no legal basis.

Danish authorities worry that a mutated form of coronavirus found in mink could potentially hamper the effectiveness of a future vaccine.

As the politicians argue, mass graves have appeared in the Danish countryside filled with the slaughtered animals.
</p>
{% endblock body %}h3

templates/addarticle.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Create Article</h3>
        <hr>
        <form method="POST" enctype="multipart/form-data">
            
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}

            <br>
            <button type="submit" class= "btn btn-primary">Add Article</button>
        </form>
    </div>
  </div>
{% endblock body %}

templates/articles.html
{% extends "layout.html" %}

{% block body %}
<h1>Articles</h1>
<hr>

{% if articles %}
{% for article in articles  %}
 <div class="row">

      <!-- Post Content Column -->
      <div class="col-lg-8">
        <form>
            {% csrf_token %}
            <div class="active-cyan-3 active-cyan-4 mb-4">
                <input name="keyword" class="form-control" type="text" placeholder="Search" button  aria-label="Search">
              </div>
            </form>
        <!-- Title -->
        <a href="/articles/article/{{article.id}}"><h3 class="mt-4">{{article.title}}</h3>
        </a>
        <!-- Author -->
        <p class="lead">
          by
          {{article.author.username}}
        </p>
        
        <hr>

        <!-- Date/Time -->
        <p>{{article.created_date}}</p>

        <hr>

        <!--Preview Image -->
        {% if article.article_image %}
        <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="">
    
        {% endif %}
        

        <hr>

        <!-- Post Content -->
        <p class="lead">
        {{article.content| safe| truncatewords:30}} 
        
        <a style="float :right" href="/articles/article/{{article.id}}" class="btn btn-success">Read Article</a> 
        <hr>
        

 
        


      </div>

    </div>
{% endfor %}

{% else %}
<div class ="alert alert-danger">
    No article in dashboard
</div>
{% endif %}
{% endblock body %}<h2>Articles</h2>

templates/dashboard.html
{% extends "layout.html" %}

{% block body %}
<h1>Dashboard</h1>
<hr>
<p>
    Welcome, <small>{{request.user.username}}</small>

</p>
<hr>
<a class="btn btn-primary" href="/articles/addarticle">Add Article</a>
<hr>
{% if articles %}
<table class="table">
    <thead>
      <tr>
        <th scope="col">id</th>
        <th scope="col">Title</th>
        <th scope="col">Author</th>
        <th scope="col">Created Date</th>
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>

    {% for article in articles %}
    <tr>
        <th scope="row">{{article.id}}</th>
        <td><a href="/articles/article/{{article.id}}">{{article.title}}</a></td>
        <td>{{article.author.username}}</td>
        <td>{{article.created_date}}</td>
        <td><a href="/articles/update/{{article.id}}" class="btn btn-primary">Change</a></td>
        <td><a href="/articles/delete/{{article.id}}" class="btn btn-danger">Delete</a></td>
    </tr>
    {% endfor %}

      <!---<tr>
        <th scope="row">1</th>
        <td>Mark</td>
        <td>Otto</td>
        <td>@mdo</td>
      </tr>--->

      
    </tbody>
  </table>
{% else %}
<div class="alert alert-danger">
You do not have any article in dashoard..
</div>
{% endif %}

{% endblock  %}

templates/detail.html
{% extends "layout.html" %}

{% block body %}
  <div class="row">

      <!-- Post Content Column -->
      <div class="col-lg-8">

        <!-- Title -->
        <h3 class="mt-4">{{article.title}}</h3>

        <!-- Author -->
        <p class="lead">
          by
          {{article.author.username}}
        </p>

        <hr>

        <!-- Date/Time -->
        <p>{{article.created_date}}</p>

        <hr>

        <!--Preview Image -->
        {% if article.article_image %}
        <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="">
    
        {% endif %}
        

        <hr>

        <!-- Post Content -->
        <p class="lead">
        {{article.content| safe}}
        

        <hr>
     
      {% if comments %}
      {% for comment in comments  %}
      <div class="media mb-4">
        <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
        <div class="media-body">
          <h5 class="mt-0">{{comment.comment_author}}</h5>
          {{comment.comment_date}} <br>
          {{comment.comment_content}}
        </div>
      </div>
      {% endfor %}s
        
      {% else %}
      <div class="alert alert_danger">No comment for this article</div>
      {% endif %}
        


   

   

     <!-- Comments Form -->
     <div class="card my-4">
      <h5 class="card-header">Leave a Comment:</h5>
      <div class="card-body">
        <form method="post" action= "{% url 'article:comment' article.id %}">
          {%csrf_token %}
          <div class="form-group">
            <label>Name</label>
            <input class="form-control" name="Author" placeholder="Enter your name">
            
          </div>
          <div class="form-group">
            <textarea class="form-control" name="Comment" rows="3" placeholder="Type your comment.."></textarea>
          </div>
          <button type="submit" class="btn btn-primary">Submit</button>
        </form>
      </div>
    </div>
{% endblock body %}

templates/includes/navbar.html
<html lang = "en">
   <head>
      <!-- Meta tags -->
      <meta charset = "utf-8">
      <meta name = "viewport" content = "width = device-width, initial-scale = 1, shrink-to-fit = no">
      
      <!-- Bootstrap CSS -->
      <link rel = "stylesheet" 
         href = "https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" 
         integrity = "sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" 
         crossorigin = "anonymous">
      
      <title>Bootstrap 4 Example</title>
   </head>
   <body>
    <div class = "container">
        <nav class = "navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
           
           <button class = "navbar-toggler" type = "button" data-toggle = "collapse" 
              data-target = "#navbarNavDropdown" aria-controls = "navbarNavDropdown" 
              aria-expanded = "false" aria-label = "Toggle navigation">
              
              <span class="navbar-toggler-icon"></span>
           </button>
            
            <div class = "collapse navbar-collapse" id = "navbarNavDropdown">
               <ul class = "navbar-nav">
                  <li class = "nav-item active">
                     <a class = "nav-link" href = "{% url 'index' %}">Home 
                        <span class = "sr-only">(current)</span>
                     </a>
                  </li>
                  <li class = "nav-item">
                     <a class = "nav-link" href = "{% url 'about' %}">About Us</a>
                  </li>
                  <li class = "nav-item">
                     <a class = "nav-link" href = "{% url 'article:articles' %}">Articles</a>
                  </li>
                        
                     </a>
                     
                  </li>
               </ul>
               <ul class="navbar-nav ml-auto">
                  
               {% if request.user.is_authenticated %}
               <li class = "nav-item">
                     <a class = "nav-link" href = "{% url 'article:dashboard' %}">Dashboard</a>
                  </li>
               <li class = "nav-item">
                     <a class = "nav-link" href = "{% url 'user:logout' %}">Logout</a>
                  </li> 
               {% else %}
               <li class = "nav-item">
                     <a class = "nav-link" href = "{% url 'user:login' %}">Login</a>
                  </li>  
               {% endif %}
               <li class = "nav-item">
                     <a class = "nav-link" href = "{% url 'user:register' %}">Sign up</a>
                  </li>
               
                  
                  
                   
               </ul>
            </div>
         </nav>
      </div>
      
      <!-- jQuery library -->
      <script src = "https://code.jquery.com/jquery-3.2.1.slim.min.js" 
         integrity =" sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" 
         crossorigin = "anonymous">
      </script>
      
      <!-- Popper -->
      <script src = "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" 
         integrity = "sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" 
         crossorigin = "anonymous">
      </script>
      
      <!-- Latest compiled and minified Bootstrap JavaScript -->
      <script src = "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" 
         integrity = "sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" 
         crossorigin =" anonymous">
      </script>
      
   </body>
</html>

templates/includes/posttemplate.html
<div class="row">

    <!-- Post Content Column -->
    <div class="col-lg-8">

      <!-- Title -->
      <h1 class="mt-4">Post Title</h1>

      <!-- Author -->
      <p class="lead">
        by
        <a href="#">Start Bootstrap</a>
      </p>

      <hr>

      <!-- Date/Time -->
      <p>Posted on January 1, 2019 at 12:00 PM</p>

      <hr>

      <!-- Preview Image -->
      <img class="img-fluid rounded" src="http://placehold.it/900x300" alt="">

      <hr>

      <!-- Post Content -->
      <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, vero, obcaecati, aut, error quam sapiente nemo saepe quibusdam sit excepturi nam quia corporis eligendi eos magni recusandae laborum minus inventore?</p>

      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus.</p>

      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos, doloribus, dolorem iusto blanditiis unde eius illum consequuntur neque dicta incidunt ullam ea hic porro optio ratione repellat perspiciatis. Enim, iure!</p>

      <blockquote class="blockquote">
        <p class="mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
        <footer class="blockquote-footer">Someone famous in
          <cite title="Source Title">Source Title</cite>
        </footer>
      </blockquote>

      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, nostrum, aliquid, animi, ut quas placeat totam sunt tempora commodi nihil ullam alias modi dicta saepe minima ab quo voluptatem obcaecati?</p>

      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum, dolor quis. Sunt, ut, explicabo, aliquam tenetur ratione tempore quidem voluptates cupiditate voluptas illo saepe quaerat numquam recusandae? Qui, necessitatibus, est!</p>

      <hr>

      <!-- Comments Form -->
      <div class="card my-4">
        <h5 class="card-header">Leave a Comment:</h5>
        <div class="card-body">
          <form>
            <div class="form-group">
              <textarea class="form-control" rows="3"></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
          </form>
        </div>
      </div>

      <!-- Single Comment -->
      <div class="media mb-4">
        <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
        <div class="media-body">
          <h5 class="mt-0">Commenter Name</h5>
          Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
        </div>
      </div>

      <!-- Comment with nested comments -->
      <div class="media mb-4">
        <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
        <div class="media-body">
          <h5 class="mt-0">Commenter Name</h5>
          Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.

          <div class="media mt-4">
            <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
            <div class="media-body">
              <h5 class="mt-0">Commenter Name</h5>
              Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
            </div>
          </div>

          <div class="media mt-4">
            <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
            <div class="media-body">
              <h5 class="mt-0">Commenter Name</h5>
              Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
            </div>
          </div>

        </div>
      </div>

    </div>

    <!-- Sidebar Widgets Column -->
    <div class="col-md-4">

      <!-- Search Widget -->
      <div class="card my-4">
        <h5 class="card-header">Search</h5>
        <div class="card-body">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search for...">
            <span class="input-group-append">
              <button class="btn btn-secondary" type="button">Go!</button>
            </span>
          </div>
        </div>
      </div>

      <!-- Categories Widget -->
      <div class="card my-4">
        <h5 class="card-header">Categories</h5>
        <div class="card-body">
          <div class="row">
            <div class="col-lg-6">
              <ul class="list-unstyled mb-0">
                <li>
                  <a href="#">Web Design</a>
                </li>
                <li>
                  <a href="#">HTML</a>
                </li>
                <li>
                  <a href="#">Freebies</a>
                </li>
              </ul>
            </div>
            <div class="col-lg-6">
              <ul class="list-unstyled mb-0">
                <li>
                  <a href="#">JavaScript</a>
                </li>
                <li>
                  <a href="#">CSS</a>
                </li>
                <li>
                  <a href="#">Tutorials</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>

      <!-- Side Widget -->
      <div class="card my-4">
        <h5 class="card-header">Side Widget</h5>
        <div class="card-body">
          You can put anything you want inside of these side widgets. They are easy to use, and feature the new Bootstrap 4 card containers!
        </div>
      </div>

    </div>

  </div>

templates/index.html
{% extends "layout.html" %}

{% block body %}

<div class="jumbotron text-center">
    <h3>Welcome to Software Blog</h3>
    <p>You can publish your entries in this blog and help other developers</p>
</div>
<p>
        {% if request.user.is_authenticated %}
            {{request.user.username}} logged in

        {% else %}
            
        {% endif %}

</p>

{% endblock body %}<h3>AnaSayfa

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/boostrap.min.css'%}">
    <title>YbBlog</title>
</head>
<body>
    {% include "includes/navbar.html" %}
   
    
    <div style= "margin-top :100px; margin-bottom :100px;" class="container">
        {% if messages %}
            
                {% for message in messages %}
                {% if message.tags == "info" %}
                <div class="alert alert-danger">{{ message }}</div>
                {% else %}
                <div class="alert alert-{{message.tags}}">{{ message }}</div>
                {% endif %}
                
                {% endfor %}
            
    {% endif %}
        {% block body %}
        
        {% endblock  %}
        
    </div>
   <script src="{% static 'js/boostrap.min.js'%}"></script>
   <script src="{% static 'js/jquery-3.2.1.min.js'%}"></script>
   <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>

</body>
</html>

templates/login.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Login</h3>
        <hr>
        <form method="POST">
            {% csrf_token %}
            {{form|crispy}}
            <br>
            <button type="submit" class= "btn btn-danger">Sign in</button>
        </form>
    </div>
  </div>

{% endblock body %}

templates/register.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Registration</h3>
        <hr>
        <form method="POST">
            {% csrf_token %}
            {{form|crispy}}
            <br>
            <button type="submit" class= "btn btn-danger">Sign up</button>
        </form>
    </div>
  </div>
{% endblock body %}

templates/update.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Update Article</h3>
        <hr>
        <form method="POST" enctype="multipart/form-data">
            
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}

            <br>
            <button type="submit" class= "btn btn-primary">Save Article</button>
        </form>
    </div>
  </div>
{% endblock body %}